### ISSUE TITLE
branch vs fork

### ISSUE THREAD

**Issue by kgonzago** [githubteacher/devs-jan-2016#30]
The workflow is highlighting branching. When would you want to fork a repo instead of branching it?

**Comment by jaw6** [comment]
A branch is a git-level technology that helps to isolate work -- in this way, you can begin work on one set of changes (a new feature, say) and switch focus to another set of changes when required (a bug fix, say) without losing or interfering with any of your earlier work (when the bug is fixed, go back to the feature branch).

A fork is a GitHub-level technology to address repository ownership and permission. When you fork a repository on GitHub, we create a new repository that's a copy of the content and history and has a link back to the original repository -- we don't copy issues and pull requests, but we do copy branches. The fork is owned by (and writable by) your user on GitHub. So, you might not be a trusted collaborator on open source Project X, but you can **fork** Project X (now you have a copy of it where you are the owner) and make your change on _your fork_ and submit a pull request _back_ to the original open source project.

Branches are used by teams that trust each other to collaboratively develop a project together. Forks are typically used by folks who aren't trusted to propose changes from outside of the core team. They can also be used to indicate a project had begun elsewhere, but is now heading in it's own direction. (For example, the [Elasticsearch project](https://en.wikipedia.org/wiki/Elasticsearch) began as a fork of the Lucene project but has taken on a life of its own.)
